### PR TITLE
Show default device icon in tray.

### PR DESCRIPTION
**Pull request by petruchito**
(Handy for the quick switch mode)
Maybe add a separate setting for this, someone may complain that this
makes the icon hard to find...

And also I don't handle nonstandard resolution, just load the icon as
is, there might be some problems.

### CODE REVIEW

**Comment by xenolightning** [comment]
I'm hesitant to merge this in. I've had a few request for this in the past.

If you want to make the feature complete, by adding a setting and checking the icon, then I will include it in a future release.

One thing to consider, is what happens when the Default Playback device is removed, or disabled from the system, currently the icon will stay constant.

**Comment by petruchito** [comment]
I've completed the feature, seems to be fully functional.
Concerning the size of the icon - I've tested it on my Win7 box on 100% and 150% dpi settings - no problems at all, icon is displayed correctly.
At first this was a small patch for myself and my wife (and a feature proposition for you), but if people asked for it...

**Comment by xenolightning** [comment]
It's been requested a few times. I released an RC version (a while back) that did this by default, and got really mixed feedback on it. Hence my request to introduce a setting to drive it the functionality required.

Everything looks to be ok in the pull request, I'll take a proper look later tonight, and merge it into master.

I've held off on a bugfix (1.6.3.1) release so if I get it all sorted, this will go out with the 1.6.3.1 release, and it will be in the main version chain going forward.

Thanks!

**Comment by xenolightning** [comment]
Just FYI the merge may not go too smoothly as your fork is behind the master, and it just so happens that I fixed a bug in the same area of the code.

Will see how it goes, you may want to sync up your fork anyway.

**Comment by petruchito** [comment]
Yep, updated my fork.

**Comment by xenolightning** [comment]
Merged and is released in 1.6.3.1, which is available via auto update + sourceforge.

**Pull request merged**
