### PR TITLE
Only allow for one client instance

### PR DESCRIPTION
**Pull request by RickDB**
This checks if AudioSwitcher client is already running and closes it if so, kept the dialog pretty basic but can of course expand on that :)

### CODE REVIEW

**Comment by xenolightning** [comment]
This was done initially, but if multi people use a computer then it requires multiple instances of the application to be open.

There was an issue a long time ago to remove the single client instance, so it won't be included back in at this stage.

**Comment by RickDB** [comment]
Ah I see, so this was done for RDP sessions :)
What could be possible is to check if one or more is running as the current user if you want, that way it still allows multiple instances if the computer has multiple active accounts.

**Comment by xenolightning** [comment]
Yeah RDP was one use case. There are also multi use PC's, where user's will switch in and out without "logging out" as such, and the application stays open.

Yeah there's a bit that could be done to make it single instance, but it there any huge downsides to running to instances of the application?

The settings get a little dodgy, but for the most part it's ok.

**Comment by RickDB** [comment]
Yeah except for the settings part it works fine, I had it overwrite it from another instance which got launched by mistake recently which isn't a big dea and less commonl tbh :)

**Pull request closed without merging**
